- name: Git push local changes
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Add, commit, and push local code
      shell: |
        git add .
        git commit -m "Auto commit from Ansible"
        git push origin master
      args:
        chdir: /home/mapubi/Desktop/LangApp/dashboard
      ignore_errors: true


- name: Deploy Multi App Dasboard
  hosts: vps
  become: true
  tasks:
    - name: Pull latest changes from repository
      ansible.builtin.git:
        repo: 'https://GODWILLTETAH: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@github.com/GODWILLTETAH/mydashboard.git'
        
        dest: /root/projects/mydashboard
        version: master
        accept_hostkey: true 

    - name: Stop containers using docker-compose
      ansible.builtin.shell: |
        cd /root/projects/mydashboard
        sudo docker-compose down

    - name: Build and start containers using docker-compose
      ansible.builtin.shell: |
        cd /root/projects/mydashboard
        sudo docker-compose up -d --build

# run this command in ansible folder to : ansible-playbook -i inventory/hosts.ini deploy.yml
