- name: Git push local changes
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Add, commit, and push local code
      shell: |
        git add .
        git commit -m "Auto commit from Ansible"
        git push origin master
      args:
        chdir: /home/mapubi/Desktop/LangApp/dashboard
      ignore_errors: true


- name: Deploy Multi App Dasboard
  hosts: vps
  become: true
  tasks:
    - name: Pull latest changes from repository
      ansible.builtin.git:
        repo: 'https://GODWILLTETAH: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@github.com/GODWILLTETAH/mydashboard.git'
        
        dest: /root/projects/mydashboard
        version: master
        accept_hostkey: true 

    - name: Stop containers using docker-compose
      ansible.builtin.shell: |
        cd /root/projects/mydashboard
        sudo docker-compose down

    - name: Build and start containers using docker-compose
      ansible.builtin.shell: |
        cd /root/projects/mydashboard
        sudo docker-compose up -d --build

# run this command in ansible folder to : ansible-playbook -i inventory/hosts.ini deploy.yml

# ssh key; ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCJeIZwr8Kn2BHTgxwcOanAoURbvDRBDTw2oCLkGaLENFpbNOuDFnc7amzyK6kJZT9A7XuBClVoShusX62BGexouP4cOzTeGKNxLlD794WGml4o+ZTbNiXsOtP1Gsn7Ry++TQH4dEhHXXEqwwYwAFO69Aa/kuZRhSaSzjdbpZGjfItNJQBg9o2d7U1AEkvYnHgzHsuMGp47b53scX0k2eXNwaSKHK8KcuZg15EoUqFkco1K1fTCofygUogMaUKJ3E545gwIBB4lKO+th4wZiz9ZqdMdgABqWVi0rZ4tGpNEbC2gzmphSzBessHzNEX9DbOBlFs/DG1VM7UUnO23hYp0QY6RQBOE+Vc2RApuRMfa2GoxWOFq1nA7HMzuJloc95X0vPU2Kf5PkXPWQX7EC8UlpaE9S0htuGaG5m1+rHJFiMGu1Hg3rY9wB6fLb0npqx/lzwrx1dHikgSPJ5GFkikmo7IMlvrFT7Ga8x7eW0goxg7Zl4MNc2gTbGh6Ji9YBseJcYnmRP/UZADdYECNlFfn6IuIteJsVXztUnsftS571aLSxFlPU9ib/A4jXK8zj/U5Capl8p0mNrC8fHy+9N8+LodWclhZVuxjXWIWhk7YEG2MfkwhZ/j6QS5fAWtIN9qlYGw6dZLY/Ju3yorbAiRhGUB1mavZQfEwhNrs/V8m1w== mapubi@mapubi-Latitude-7480
